source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DMPickerView_Example', :exclusive => true do
  pod "DMPickerView", :path => "../"
end

target 'DMPickerView_Tests', :exclusive => true do
  pod "DMPickerView", :path => "../"

  
end
